name: build

on:
  push:
    tags:
      - "*"

jobs:
  build-binary:
    strategy:
      matrix:
        GOARCH: ["amd64", "arm64"]
        GOOS: ["linux", "darwin"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true
      - run: go build ./cmd/web5-components-tests
        env:
          GOARCH: ${{ matrix.GOARCH }}
          GOOS: ${{ matrix.GOOS }}
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{  github.ref_name }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v3
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          name: web5-components-tests-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: web5-components-tests
