name: build

on:
  push:
    tags:
      - "*"

jobs:
  build-binary:
    strategy:
      matrix:
        GOARCH: ["amd64", "arm64"]
        GOOS: ["linux", "darwin"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true
      - run: go build ./cmd/web5-components-tests
        env:
          GOARCH: ${{ matrix.GOARCH }}
          GOOS: ${{ matrix.GOOS }}
      - uses: actions/upload-artifact@v3
        with:
          name: web5-components-tests-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: web5-components-tests
  create-release:
    needs: [build-binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -R
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            web5-components-tests-linux-amd64
            web5-components-tests-linux-arm64
            web5-components-tests-darwin-amd64
            web5-components-tests-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
