name: System Test

on:
  push:
    branches:
    - main
    - test/**
  pull_request:
      branches:
      - main

jobs:
  systemtest:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content to github runner.

    - name: Start Containers
      # run: docker-compose -f "docker-compose.yml" up -d --build
      run: docker-compose build --no-cache && docker-compose up

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install requirements.txt
      run: pip install -r tests/requirements.txt
    
    - name: Run tests
      working-directory: ./tests
      run: python 0-all-tests.py

    - name: Stop Containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down